package com.peersafe.chainsql.crypto;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MultiEncrypt.proto

public final class EncryptMsg {
  private EncryptMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MultiEncryptOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bytes public_other = 1;
    /**
     * <code>required bytes public_other = 1;</code>
     *
     * <pre>
     *DH 随机产生的公钥
     * </pre>
     */
    boolean hasPublicOther();
    /**
     * <code>required bytes public_other = 1;</code>
     *
     * <pre>
     *DH 随机产生的公钥
     * </pre>
     */
    com.google.protobuf.ByteString getPublicOther();

    // repeated .MultiEncrypt.HashToken hash_token_pair = 2;
    /**
     * <code>repeated .MultiEncrypt.HashToken hash_token_pair = 2;</code>
     *
     * <pre>
     *公钥哈希与Token数组
     * </pre>
     */
    java.util.List<EncryptMsg.MultiEncrypt.HashToken> 
        getHashTokenPairList();
    /**
     * <code>repeated .MultiEncrypt.HashToken hash_token_pair = 2;</code>
     *
     * <pre>
     *公钥哈希与Token数组
     * </pre>
     */
    EncryptMsg.MultiEncrypt.HashToken getHashTokenPair(int index);
    /**
     * <code>repeated .MultiEncrypt.HashToken hash_token_pair = 2;</code>
     *
     * <pre>
     *公钥哈希与Token数组
     * </pre>
     */
    int getHashTokenPairCount();
    /**
     * <code>repeated .MultiEncrypt.HashToken hash_token_pair = 2;</code>
     *
     * <pre>
     *公钥哈希与Token数组
     * </pre>
     */
    java.util.List<? extends EncryptMsg.MultiEncrypt.HashTokenOrBuilder> 
        getHashTokenPairOrBuilderList();
    /**
     * <code>repeated .MultiEncrypt.HashToken hash_token_pair = 2;</code>
     *
     * <pre>
     *公钥哈希与Token数组
     * </pre>
     */
    EncryptMsg.MultiEncrypt.HashTokenOrBuilder getHashTokenPairOrBuilder(
        int index);

    // required bytes cipher = 3;
    /**
     * <code>required bytes cipher = 3;</code>
     *
     * <pre>
     *字符串的密文
     * </pre>
     */
    boolean hasCipher();
    /**
     * <code>required bytes cipher = 3;</code>
     *
     * <pre>
     *字符串的密文
     * </pre>
     */
    com.google.protobuf.ByteString getCipher();
  }
  /**
   * Protobuf type {@code MultiEncrypt}
   */
  public static final class MultiEncrypt extends
      com.google.protobuf.GeneratedMessage
      implements MultiEncryptOrBuilder {
    // Use MultiEncrypt.newBuilder() to construct.
    private MultiEncrypt(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MultiEncrypt(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MultiEncrypt defaultInstance;
    public static MultiEncrypt getDefaultInstance() {
      return defaultInstance;
    }

    public MultiEncrypt getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MultiEncrypt(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              publicOther_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                hashTokenPair_ = new java.util.ArrayList<EncryptMsg.MultiEncrypt.HashToken>();
                mutable_bitField0_ |= 0x00000002;
              }
              hashTokenPair_.add(input.readMessage(EncryptMsg.MultiEncrypt.HashToken.PARSER, extensionRegistry));
              break;
            }
            case 26: {
              bitField0_ |= 0x00000002;
              cipher_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          hashTokenPair_ = java.util.Collections.unmodifiableList(hashTokenPair_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EncryptMsg.internal_static_MultiEncrypt_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EncryptMsg.internal_static_MultiEncrypt_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EncryptMsg.MultiEncrypt.class, EncryptMsg.MultiEncrypt.Builder.class);
    }

    public static com.google.protobuf.Parser<MultiEncrypt> PARSER =
        new com.google.protobuf.AbstractParser<MultiEncrypt>() {
      public MultiEncrypt parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MultiEncrypt(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MultiEncrypt> getParserForType() {
      return PARSER;
    }

    public interface HashTokenOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required bytes public_hash = 1;
      /**
       * <code>required bytes public_hash = 1;</code>
       */
      boolean hasPublicHash();
      /**
       * <code>required bytes public_hash = 1;</code>
       */
      com.google.protobuf.ByteString getPublicHash();

      // required bytes token = 2;
      /**
       * <code>required bytes token = 2;</code>
       */
      boolean hasToken();
      /**
       * <code>required bytes token = 2;</code>
       */
      com.google.protobuf.ByteString getToken();
    }
    /**
     * Protobuf type {@code MultiEncrypt.HashToken}
     */
    public static final class HashToken extends
        com.google.protobuf.GeneratedMessage
        implements HashTokenOrBuilder {
      // Use HashToken.newBuilder() to construct.
      private HashToken(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private HashToken(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final HashToken defaultInstance;
      public static HashToken getDefaultInstance() {
        return defaultInstance;
      }

      public HashToken getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private HashToken(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                publicHash_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                token_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EncryptMsg.internal_static_MultiEncrypt_HashToken_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EncryptMsg.internal_static_MultiEncrypt_HashToken_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EncryptMsg.MultiEncrypt.HashToken.class, EncryptMsg.MultiEncrypt.HashToken.Builder.class);
      }

      public static com.google.protobuf.Parser<HashToken> PARSER =
          new com.google.protobuf.AbstractParser<HashToken>() {
        public HashToken parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new HashToken(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<HashToken> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required bytes public_hash = 1;
      public static final int PUBLIC_HASH_FIELD_NUMBER = 1;
      private com.google.protobuf.ByteString publicHash_;
      /**
       * <code>required bytes public_hash = 1;</code>
       */
      public boolean hasPublicHash() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes public_hash = 1;</code>
       */
      public com.google.protobuf.ByteString getPublicHash() {
        return publicHash_;
      }

      // required bytes token = 2;
      public static final int TOKEN_FIELD_NUMBER = 2;
      private com.google.protobuf.ByteString token_;
      /**
       * <code>required bytes token = 2;</code>
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes token = 2;</code>
       */
      public com.google.protobuf.ByteString getToken() {
        return token_;
      }

      private void initFields() {
        publicHash_ = com.google.protobuf.ByteString.EMPTY;
        token_ = com.google.protobuf.ByteString.EMPTY;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasPublicHash()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasToken()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, publicHash_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, token_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, publicHash_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, token_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static EncryptMsg.MultiEncrypt.HashToken parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static EncryptMsg.MultiEncrypt.HashToken parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static EncryptMsg.MultiEncrypt.HashToken parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static EncryptMsg.MultiEncrypt.HashToken parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static EncryptMsg.MultiEncrypt.HashToken parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static EncryptMsg.MultiEncrypt.HashToken parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static EncryptMsg.MultiEncrypt.HashToken parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static EncryptMsg.MultiEncrypt.HashToken parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static EncryptMsg.MultiEncrypt.HashToken parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static EncryptMsg.MultiEncrypt.HashToken parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(EncryptMsg.MultiEncrypt.HashToken prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code MultiEncrypt.HashToken}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements EncryptMsg.MultiEncrypt.HashTokenOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return EncryptMsg.internal_static_MultiEncrypt_HashToken_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return EncryptMsg.internal_static_MultiEncrypt_HashToken_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  EncryptMsg.MultiEncrypt.HashToken.class, EncryptMsg.MultiEncrypt.HashToken.Builder.class);
        }

        // Construct using EncryptMsg.MultiEncrypt.HashToken.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          publicHash_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          token_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return EncryptMsg.internal_static_MultiEncrypt_HashToken_descriptor;
        }

        public EncryptMsg.MultiEncrypt.HashToken getDefaultInstanceForType() {
          return EncryptMsg.MultiEncrypt.HashToken.getDefaultInstance();
        }

        public EncryptMsg.MultiEncrypt.HashToken build() {
          EncryptMsg.MultiEncrypt.HashToken result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public EncryptMsg.MultiEncrypt.HashToken buildPartial() {
          EncryptMsg.MultiEncrypt.HashToken result = new EncryptMsg.MultiEncrypt.HashToken(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.publicHash_ = publicHash_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.token_ = token_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof EncryptMsg.MultiEncrypt.HashToken) {
            return mergeFrom((EncryptMsg.MultiEncrypt.HashToken)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(EncryptMsg.MultiEncrypt.HashToken other) {
          if (other == EncryptMsg.MultiEncrypt.HashToken.getDefaultInstance()) return this;
          if (other.hasPublicHash()) {
            setPublicHash(other.getPublicHash());
          }
          if (other.hasToken()) {
            setToken(other.getToken());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasPublicHash()) {
            
            return false;
          }
          if (!hasToken()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          EncryptMsg.MultiEncrypt.HashToken parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (EncryptMsg.MultiEncrypt.HashToken) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required bytes public_hash = 1;
        private com.google.protobuf.ByteString publicHash_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>required bytes public_hash = 1;</code>
         */
        public boolean hasPublicHash() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required bytes public_hash = 1;</code>
         */
        public com.google.protobuf.ByteString getPublicHash() {
          return publicHash_;
        }
        /**
         * <code>required bytes public_hash = 1;</code>
         */
        public Builder setPublicHash(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          publicHash_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bytes public_hash = 1;</code>
         */
        public Builder clearPublicHash() {
          bitField0_ = (bitField0_ & ~0x00000001);
          publicHash_ = getDefaultInstance().getPublicHash();
          onChanged();
          return this;
        }

        // required bytes token = 2;
        private com.google.protobuf.ByteString token_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>required bytes token = 2;</code>
         */
        public boolean hasToken() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required bytes token = 2;</code>
         */
        public com.google.protobuf.ByteString getToken() {
          return token_;
        }
        /**
         * <code>required bytes token = 2;</code>
         */
        public Builder setToken(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          token_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bytes token = 2;</code>
         */
        public Builder clearToken() {
          bitField0_ = (bitField0_ & ~0x00000002);
          token_ = getDefaultInstance().getToken();
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:MultiEncrypt.HashToken)
      }

      static {
        defaultInstance = new HashToken(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:MultiEncrypt.HashToken)
    }

    private int bitField0_;
    // required bytes public_other = 1;
    public static final int PUBLIC_OTHER_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString publicOther_;
    /**
     * <code>required bytes public_other = 1;</code>
     *
     * <pre>
     *DH 随机产生的公钥
     * </pre>
     */
    public boolean hasPublicOther() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes public_other = 1;</code>
     *
     * <pre>
     *DH 随机产生的公钥
     * </pre>
     */
    public com.google.protobuf.ByteString getPublicOther() {
      return publicOther_;
    }

    // repeated .MultiEncrypt.HashToken hash_token_pair = 2;
    public static final int HASH_TOKEN_PAIR_FIELD_NUMBER = 2;
    private java.util.List<EncryptMsg.MultiEncrypt.HashToken> hashTokenPair_;
    /**
     * <code>repeated .MultiEncrypt.HashToken hash_token_pair = 2;</code>
     *
     * <pre>
     *公钥哈希与Token数组
     * </pre>
     */
    public java.util.List<EncryptMsg.MultiEncrypt.HashToken> getHashTokenPairList() {
      return hashTokenPair_;
    }
    /**
     * <code>repeated .MultiEncrypt.HashToken hash_token_pair = 2;</code>
     *
     * <pre>
     *公钥哈希与Token数组
     * </pre>
     */
    public java.util.List<? extends EncryptMsg.MultiEncrypt.HashTokenOrBuilder> 
        getHashTokenPairOrBuilderList() {
      return hashTokenPair_;
    }
    /**
     * <code>repeated .MultiEncrypt.HashToken hash_token_pair = 2;</code>
     *
     * <pre>
     *公钥哈希与Token数组
     * </pre>
     */
    public int getHashTokenPairCount() {
      return hashTokenPair_.size();
    }
    /**
     * <code>repeated .MultiEncrypt.HashToken hash_token_pair = 2;</code>
     *
     * <pre>
     *公钥哈希与Token数组
     * </pre>
     */
    public EncryptMsg.MultiEncrypt.HashToken getHashTokenPair(int index) {
      return hashTokenPair_.get(index);
    }
    /**
     * <code>repeated .MultiEncrypt.HashToken hash_token_pair = 2;</code>
     *
     * <pre>
     *公钥哈希与Token数组
     * </pre>
     */
    public EncryptMsg.MultiEncrypt.HashTokenOrBuilder getHashTokenPairOrBuilder(
        int index) {
      return hashTokenPair_.get(index);
    }

    // required bytes cipher = 3;
    public static final int CIPHER_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString cipher_;
    /**
     * <code>required bytes cipher = 3;</code>
     *
     * <pre>
     *字符串的密文
     * </pre>
     */
    public boolean hasCipher() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes cipher = 3;</code>
     *
     * <pre>
     *字符串的密文
     * </pre>
     */
    public com.google.protobuf.ByteString getCipher() {
      return cipher_;
    }

    private void initFields() {
      publicOther_ = com.google.protobuf.ByteString.EMPTY;
      hashTokenPair_ = java.util.Collections.emptyList();
      cipher_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasPublicOther()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCipher()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getHashTokenPairCount(); i++) {
        if (!getHashTokenPair(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, publicOther_);
      }
      for (int i = 0; i < hashTokenPair_.size(); i++) {
        output.writeMessage(2, hashTokenPair_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, cipher_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, publicOther_);
      }
      for (int i = 0; i < hashTokenPair_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, hashTokenPair_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, cipher_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static EncryptMsg.MultiEncrypt parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EncryptMsg.MultiEncrypt parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EncryptMsg.MultiEncrypt parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EncryptMsg.MultiEncrypt parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EncryptMsg.MultiEncrypt parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static EncryptMsg.MultiEncrypt parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static EncryptMsg.MultiEncrypt parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static EncryptMsg.MultiEncrypt parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static EncryptMsg.MultiEncrypt parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static EncryptMsg.MultiEncrypt parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(EncryptMsg.MultiEncrypt prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MultiEncrypt}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements EncryptMsg.MultiEncryptOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EncryptMsg.internal_static_MultiEncrypt_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EncryptMsg.internal_static_MultiEncrypt_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EncryptMsg.MultiEncrypt.class, EncryptMsg.MultiEncrypt.Builder.class);
      }

      // Construct using EncryptMsg.MultiEncrypt.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHashTokenPairFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        publicOther_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (hashTokenPairBuilder_ == null) {
          hashTokenPair_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          hashTokenPairBuilder_.clear();
        }
        cipher_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EncryptMsg.internal_static_MultiEncrypt_descriptor;
      }

      public EncryptMsg.MultiEncrypt getDefaultInstanceForType() {
        return EncryptMsg.MultiEncrypt.getDefaultInstance();
      }

      public EncryptMsg.MultiEncrypt build() {
        EncryptMsg.MultiEncrypt result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public EncryptMsg.MultiEncrypt buildPartial() {
        EncryptMsg.MultiEncrypt result = new EncryptMsg.MultiEncrypt(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.publicOther_ = publicOther_;
        if (hashTokenPairBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            hashTokenPair_ = java.util.Collections.unmodifiableList(hashTokenPair_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.hashTokenPair_ = hashTokenPair_;
        } else {
          result.hashTokenPair_ = hashTokenPairBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cipher_ = cipher_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EncryptMsg.MultiEncrypt) {
          return mergeFrom((EncryptMsg.MultiEncrypt)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EncryptMsg.MultiEncrypt other) {
        if (other == EncryptMsg.MultiEncrypt.getDefaultInstance()) return this;
        if (other.hasPublicOther()) {
          setPublicOther(other.getPublicOther());
        }
        if (hashTokenPairBuilder_ == null) {
          if (!other.hashTokenPair_.isEmpty()) {
            if (hashTokenPair_.isEmpty()) {
              hashTokenPair_ = other.hashTokenPair_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureHashTokenPairIsMutable();
              hashTokenPair_.addAll(other.hashTokenPair_);
            }
            onChanged();
          }
        } else {
          if (!other.hashTokenPair_.isEmpty()) {
            if (hashTokenPairBuilder_.isEmpty()) {
              hashTokenPairBuilder_.dispose();
              hashTokenPairBuilder_ = null;
              hashTokenPair_ = other.hashTokenPair_;
              bitField0_ = (bitField0_ & ~0x00000002);
              hashTokenPairBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getHashTokenPairFieldBuilder() : null;
            } else {
              hashTokenPairBuilder_.addAllMessages(other.hashTokenPair_);
            }
          }
        }
        if (other.hasCipher()) {
          setCipher(other.getCipher());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPublicOther()) {
          
          return false;
        }
        if (!hasCipher()) {
          
          return false;
        }
        for (int i = 0; i < getHashTokenPairCount(); i++) {
          if (!getHashTokenPair(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        EncryptMsg.MultiEncrypt parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (EncryptMsg.MultiEncrypt) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bytes public_other = 1;
      private com.google.protobuf.ByteString publicOther_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes public_other = 1;</code>
       *
       * <pre>
       *DH 随机产生的公钥
       * </pre>
       */
      public boolean hasPublicOther() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes public_other = 1;</code>
       *
       * <pre>
       *DH 随机产生的公钥
       * </pre>
       */
      public com.google.protobuf.ByteString getPublicOther() {
        return publicOther_;
      }
      /**
       * <code>required bytes public_other = 1;</code>
       *
       * <pre>
       *DH 随机产生的公钥
       * </pre>
       */
      public Builder setPublicOther(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        publicOther_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes public_other = 1;</code>
       *
       * <pre>
       *DH 随机产生的公钥
       * </pre>
       */
      public Builder clearPublicOther() {
        bitField0_ = (bitField0_ & ~0x00000001);
        publicOther_ = getDefaultInstance().getPublicOther();
        onChanged();
        return this;
      }

      // repeated .MultiEncrypt.HashToken hash_token_pair = 2;
      private java.util.List<EncryptMsg.MultiEncrypt.HashToken> hashTokenPair_ =
        java.util.Collections.emptyList();
      private void ensureHashTokenPairIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          hashTokenPair_ = new java.util.ArrayList<EncryptMsg.MultiEncrypt.HashToken>(hashTokenPair_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          EncryptMsg.MultiEncrypt.HashToken, EncryptMsg.MultiEncrypt.HashToken.Builder, EncryptMsg.MultiEncrypt.HashTokenOrBuilder> hashTokenPairBuilder_;

      /**
       * <code>repeated .MultiEncrypt.HashToken hash_token_pair = 2;</code>
       *
       * <pre>
       *公钥哈希与Token数组
       * </pre>
       */
      public java.util.List<EncryptMsg.MultiEncrypt.HashToken> getHashTokenPairList() {
        if (hashTokenPairBuilder_ == null) {
          return java.util.Collections.unmodifiableList(hashTokenPair_);
        } else {
          return hashTokenPairBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .MultiEncrypt.HashToken hash_token_pair = 2;</code>
       *
       * <pre>
       *公钥哈希与Token数组
       * </pre>
       */
      public int getHashTokenPairCount() {
        if (hashTokenPairBuilder_ == null) {
          return hashTokenPair_.size();
        } else {
          return hashTokenPairBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .MultiEncrypt.HashToken hash_token_pair = 2;</code>
       *
       * <pre>
       *公钥哈希与Token数组
       * </pre>
       */
      public EncryptMsg.MultiEncrypt.HashToken getHashTokenPair(int index) {
        if (hashTokenPairBuilder_ == null) {
          return hashTokenPair_.get(index);
        } else {
          return hashTokenPairBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .MultiEncrypt.HashToken hash_token_pair = 2;</code>
       *
       * <pre>
       *公钥哈希与Token数组
       * </pre>
       */
      public Builder setHashTokenPair(
          int index, EncryptMsg.MultiEncrypt.HashToken value) {
        if (hashTokenPairBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHashTokenPairIsMutable();
          hashTokenPair_.set(index, value);
          onChanged();
        } else {
          hashTokenPairBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MultiEncrypt.HashToken hash_token_pair = 2;</code>
       *
       * <pre>
       *公钥哈希与Token数组
       * </pre>
       */
      public Builder setHashTokenPair(
          int index, EncryptMsg.MultiEncrypt.HashToken.Builder builderForValue) {
        if (hashTokenPairBuilder_ == null) {
          ensureHashTokenPairIsMutable();
          hashTokenPair_.set(index, builderForValue.build());
          onChanged();
        } else {
          hashTokenPairBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MultiEncrypt.HashToken hash_token_pair = 2;</code>
       *
       * <pre>
       *公钥哈希与Token数组
       * </pre>
       */
      public Builder addHashTokenPair(EncryptMsg.MultiEncrypt.HashToken value) {
        if (hashTokenPairBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHashTokenPairIsMutable();
          hashTokenPair_.add(value);
          onChanged();
        } else {
          hashTokenPairBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .MultiEncrypt.HashToken hash_token_pair = 2;</code>
       *
       * <pre>
       *公钥哈希与Token数组
       * </pre>
       */
      public Builder addHashTokenPair(
          int index, EncryptMsg.MultiEncrypt.HashToken value) {
        if (hashTokenPairBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHashTokenPairIsMutable();
          hashTokenPair_.add(index, value);
          onChanged();
        } else {
          hashTokenPairBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MultiEncrypt.HashToken hash_token_pair = 2;</code>
       *
       * <pre>
       *公钥哈希与Token数组
       * </pre>
       */
      public Builder addHashTokenPair(
          EncryptMsg.MultiEncrypt.HashToken.Builder builderForValue) {
        if (hashTokenPairBuilder_ == null) {
          ensureHashTokenPairIsMutable();
          hashTokenPair_.add(builderForValue.build());
          onChanged();
        } else {
          hashTokenPairBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MultiEncrypt.HashToken hash_token_pair = 2;</code>
       *
       * <pre>
       *公钥哈希与Token数组
       * </pre>
       */
      public Builder addHashTokenPair(
          int index, EncryptMsg.MultiEncrypt.HashToken.Builder builderForValue) {
        if (hashTokenPairBuilder_ == null) {
          ensureHashTokenPairIsMutable();
          hashTokenPair_.add(index, builderForValue.build());
          onChanged();
        } else {
          hashTokenPairBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MultiEncrypt.HashToken hash_token_pair = 2;</code>
       *
       * <pre>
       *公钥哈希与Token数组
       * </pre>
       */
      public Builder addAllHashTokenPair(
          java.lang.Iterable<? extends EncryptMsg.MultiEncrypt.HashToken> values) {
        if (hashTokenPairBuilder_ == null) {
          ensureHashTokenPairIsMutable();
          super.addAll(values, hashTokenPair_);
          onChanged();
        } else {
          hashTokenPairBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .MultiEncrypt.HashToken hash_token_pair = 2;</code>
       *
       * <pre>
       *公钥哈希与Token数组
       * </pre>
       */
      public Builder clearHashTokenPair() {
        if (hashTokenPairBuilder_ == null) {
          hashTokenPair_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          hashTokenPairBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .MultiEncrypt.HashToken hash_token_pair = 2;</code>
       *
       * <pre>
       *公钥哈希与Token数组
       * </pre>
       */
      public Builder removeHashTokenPair(int index) {
        if (hashTokenPairBuilder_ == null) {
          ensureHashTokenPairIsMutable();
          hashTokenPair_.remove(index);
          onChanged();
        } else {
          hashTokenPairBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .MultiEncrypt.HashToken hash_token_pair = 2;</code>
       *
       * <pre>
       *公钥哈希与Token数组
       * </pre>
       */
      public EncryptMsg.MultiEncrypt.HashToken.Builder getHashTokenPairBuilder(
          int index) {
        return getHashTokenPairFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .MultiEncrypt.HashToken hash_token_pair = 2;</code>
       *
       * <pre>
       *公钥哈希与Token数组
       * </pre>
       */
      public EncryptMsg.MultiEncrypt.HashTokenOrBuilder getHashTokenPairOrBuilder(
          int index) {
        if (hashTokenPairBuilder_ == null) {
          return hashTokenPair_.get(index);  } else {
          return hashTokenPairBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .MultiEncrypt.HashToken hash_token_pair = 2;</code>
       *
       * <pre>
       *公钥哈希与Token数组
       * </pre>
       */
      public java.util.List<? extends EncryptMsg.MultiEncrypt.HashTokenOrBuilder> 
           getHashTokenPairOrBuilderList() {
        if (hashTokenPairBuilder_ != null) {
          return hashTokenPairBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(hashTokenPair_);
        }
      }
      /**
       * <code>repeated .MultiEncrypt.HashToken hash_token_pair = 2;</code>
       *
       * <pre>
       *公钥哈希与Token数组
       * </pre>
       */
      public EncryptMsg.MultiEncrypt.HashToken.Builder addHashTokenPairBuilder() {
        return getHashTokenPairFieldBuilder().addBuilder(
            EncryptMsg.MultiEncrypt.HashToken.getDefaultInstance());
      }
      /**
       * <code>repeated .MultiEncrypt.HashToken hash_token_pair = 2;</code>
       *
       * <pre>
       *公钥哈希与Token数组
       * </pre>
       */
      public EncryptMsg.MultiEncrypt.HashToken.Builder addHashTokenPairBuilder(
          int index) {
        return getHashTokenPairFieldBuilder().addBuilder(
            index, EncryptMsg.MultiEncrypt.HashToken.getDefaultInstance());
      }
      /**
       * <code>repeated .MultiEncrypt.HashToken hash_token_pair = 2;</code>
       *
       * <pre>
       *公钥哈希与Token数组
       * </pre>
       */
      public java.util.List<EncryptMsg.MultiEncrypt.HashToken.Builder> 
           getHashTokenPairBuilderList() {
        return getHashTokenPairFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          EncryptMsg.MultiEncrypt.HashToken, EncryptMsg.MultiEncrypt.HashToken.Builder, EncryptMsg.MultiEncrypt.HashTokenOrBuilder> 
          getHashTokenPairFieldBuilder() {
        if (hashTokenPairBuilder_ == null) {
          hashTokenPairBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              EncryptMsg.MultiEncrypt.HashToken, EncryptMsg.MultiEncrypt.HashToken.Builder, EncryptMsg.MultiEncrypt.HashTokenOrBuilder>(
                  hashTokenPair_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          hashTokenPair_ = null;
        }
        return hashTokenPairBuilder_;
      }

      // required bytes cipher = 3;
      private com.google.protobuf.ByteString cipher_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes cipher = 3;</code>
       *
       * <pre>
       *字符串的密文
       * </pre>
       */
      public boolean hasCipher() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes cipher = 3;</code>
       *
       * <pre>
       *字符串的密文
       * </pre>
       */
      public com.google.protobuf.ByteString getCipher() {
        return cipher_;
      }
      /**
       * <code>required bytes cipher = 3;</code>
       *
       * <pre>
       *字符串的密文
       * </pre>
       */
      public Builder setCipher(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        cipher_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes cipher = 3;</code>
       *
       * <pre>
       *字符串的密文
       * </pre>
       */
      public Builder clearCipher() {
        bitField0_ = (bitField0_ & ~0x00000004);
        cipher_ = getDefaultInstance().getCipher();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MultiEncrypt)
    }

    static {
      defaultInstance = new MultiEncrypt(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MultiEncrypt)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MultiEncrypt_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MultiEncrypt_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MultiEncrypt_HashToken_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MultiEncrypt_HashToken_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022MultiEncrypt.proto\"\227\001\n\014MultiEncrypt\022\024\n" +
      "\014public_other\030\001 \002(\014\0220\n\017hash_token_pair\030\002" +
      " \003(\0132\027.MultiEncrypt.HashToken\022\016\n\006cipher\030" +
      "\003 \002(\014\032/\n\tHashToken\022\023\n\013public_hash\030\001 \002(\014\022" +
      "\r\n\005token\030\002 \002(\014B\014B\nEncryptMsg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_MultiEncrypt_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_MultiEncrypt_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MultiEncrypt_descriptor,
              new java.lang.String[] { "PublicOther", "HashTokenPair", "Cipher", });
          internal_static_MultiEncrypt_HashToken_descriptor =
            internal_static_MultiEncrypt_descriptor.getNestedTypes().get(0);
          internal_static_MultiEncrypt_HashToken_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MultiEncrypt_HashToken_descriptor,
              new java.lang.String[] { "PublicHash", "Token", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
